# This Docker Compose file can be used to quickly bootup Dgraph Zero
# and Alpha in different Docker containers.

# It mounts /tmp/data on the host machine to /dgraph within the
# container. You can change /tmp/data to a more appropriate location.
# Run `docker-compose up` to start Dgraph.

version: "3.2"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    ports:
      - 8090:8080
    environment:
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
    volumes:
     - ./keycloak/data:/opt/keycloak/data/
    command: start-dev
  zero:
    image: ghcr.io/libremfg/baas:22.11.01
    volumes:
      - ./zero/data:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
    container_name: zero
  alpha:
    image: ghcr.io/libremfg/baas:22.11.01
    volumes:
      - ./alpha/data:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
#    env_file:
#      - ACCESS_KEYS.txt
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080  --security whitelist=0.0.0.0/0 --oidc bypass=false;url=http://keycloak:8080;realm=libre;client-id=libreBaas;client-secret=pk98t8jVtwF9P8erRHZpLklWtz1TzGTR
    container_name: alpha
    healthcheck:
      interval: 5s
      timeout: 3s
      retries: 5
      test: ["CMD", "curl", "-f", "http://alpha:8080/admin"]

  dgraph-init:
    image: ghcr.io/libremfg/baas:22.11.01
    volumes:
      - ./schema:/dgraph/schema
    command: >
      sh -c "curl -X POST alpha:8080/admin/schema --data-binary '@./schema/libreSchema.sdl' &&
             dgraph live -f ./schema/g01.rdf.gz -a alpha:9080 -z zero:5080"
    container_name: dgraph-init
    #depends_on:
    #  alpha:
    #      condition: service_healthy

